name: ristos
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.2
  device_info_plus: ^9.1.1
  excel: ^3.0.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.8
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  line_icons: ^2.0.3
  maps_launcher: ^2.2.0
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#000000"
  image: "assets/ristos_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/login.png
    - assets/menu.png
    - assets/settings.png
    - assets/delete.png
    - assets/add.png
    - assets/cool.jpg
    - assets/ristos_logo.png
    - assets/logo_rounded.png
  
